### ISSUE TITLE
Any way of running without `OES_texture_float`?

### ISSUE THREAD

**Issue by wiped1** [sirxemic/jquery.ripples#14]
I'm using Qt 5.5.0 Canvas3D and am wondering if there is a way for ripples texture to use gl.UNSIGNED_BYTE instead of gl.FLOAT. My attempts at doing that were unsuccessful, and I'm having a hard time, because I'm just beginning with GLSL and WebGL. Any suggestions how to tackle that problem?

**Comment by sirxemic** [comment]
Sorry for this late response, but I've experimented using gl.UNSIGNED_BYTE before, but couldn't make it work in any decent way without what I suspect would be a significant rewrite. Such a rewrite would consist of the following:

- Use several textures instead of one to keep track of the height (`r`), velocity (`g`) and normal (`b` and `a`) components. (See the fragment shaders)
- Use packing and unpacking functions to store/read (half-)floats into/from two unsigned bytes. 

But even by doing that I don't know for sure if it would actually work.

**Comment by wiped1** [comment]
Thanks for that insight, as you say it would be too much of a hassle to rewrite it with unsigned byte support.
