### ISSUE TITLE
Does not work in IE 11

### ISSUE THREAD

**Issue by akmiecik** [sirxemic/jquery.ripples#2]
When I run it in IE I get the message "TypeError: Object doesn't support property or method 'ripples'"

**Comment by Madebym** [comment]
Maybe I am missing something, but the demo doesn't work in IE11. Also, the downloaded files that use 0.2.0 version doesn't work.

Has it been fixed in the latest version?

**Comment by sirxemic** [comment]
The curent version does work in IE11 on my PC, so any more details are welcome.

**Comment by Madebym** [comment]
On my PC it shows the bg images for a split second and then all bg's turn to white. If I open developer tools in IE and change document mode and user agent to IE10, then the error info is displayed.

I am talking about your demo, but the same thing is when I use the downloaded files or play with ripples on my own.

Is there any info I could pull from IE so that you could compare it to your version. When I click about in IE, it clearly states that the version is 11.

I will put up a test link today and see if that works on your end. Will post it here.

**Comment by sirxemic** [comment]
That link works for me in IE11. But you're saying you do see an error message as well?
It would be really useful if you showed me the error you are getting.

**Comment by Madebym** [comment]
The error I am getting is only displayed if I emulate IE to version 10 in developer tools. The one that is displayed if the browser doesn't support WebGL.

If I don't emulate, and use IE normally, I see white bg. But the aniamtion is certainly there, I can feel the lag when hovering over the links, guess it is something with the bg image not displayed.

What is strange, is that you can see everything normally, while I can't and we are both using the same version of IE.

**Comment by Madebym** [comment]
Guess I missed the most obvious thing. I needed to update IE with the following update:

https://support.microsoft.com/en-us/kb/2929437/

In the description it says that it updares Internet Explorer WebGL renderer. All is fine now.

**Comment by ornaxis** [comment]
So this plugin wont work without the users manually updating their WebGL renderer? Because my IE 11 is doing the same thing.

**Comment by sirxemic** [comment]
@ornaxis Any bit of information is welcome. Does anything appear in the console log? Perhaps also remove the try-catch lines so that more details about the error is logged.

I wanted to tackle this problem before, but once Madebym updated his IE, it was too late...

**Comment by sirxemic** [comment]
Closing this until someone can help me out with more details (if it still happens at all in the first place)
