### ISSUE TITLE
Mobile devices

### ISSUE THREAD

**Issue by cvaca7** [sirxemic/jquery.ripples#26]
This awesome plugin works in any way on mobile devices?

**Comment by sirxemic** [comment]
Maybe. For now it doesn't on most, because most mobile devices don't support rendering to floating point textures, a feature which is crucial at the moment. I have something in mind which might make it work on mobile devices, but I'm not really sure about it. I may give it a shot next week when I have quite some time to spare.

**Comment by sirxemic** [comment]
So yesterday I discovered that some mobile devices do support rendering to _half_-floating point textures, making mobile device support much more trivial to implement than I previously thought. Expect a new version with mobile support very soon.

**Comment by sirxemic** [comment]
And done! See https://github.com/sirxemic/jquery.ripples/releases/tag/v0.5.3

**Comment by cvaca7** [comment]
Cool, probe it. Congratulations man.

2016-09-11 15:04 GMT-06:00 Pim Schreurs <notifications@github.com>:

**Comment by mahedihasannoman** [comment]
Hi, it still does not work for mobile browser. I have tested with Samsung Mobile and chrome browser. I am using the latest package.
Please advice.

**Comment by sirxemic** [comment]
@mahedihasannoman If [this](https://sirxemic.github.io/jquery.ripples/) doesn't work in your browser, then your browser just isn't supported. This plugin requires WebGL and support for rendering to floating point textures.
